# Generated by Django 4.0.5 on 2022-08-31 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='category_img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('product_img', models.ImageField(upload_to='product_images')),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateField(default=datetime.datetime(2022, 8, 31, 19, 37, 13, 587679))),
                ('category', models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
