# Generated by Django 4.0.5 on 2022-09-06 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 20, 34, 56, 246231)),
        ),
    ]
