# Generated by Django 4.1.1 on 2022-10-26 10:27

import datetime
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_created_at_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 26, 15, 57, 43, 617392)),
        ),
    ]
