# Generated by Django 4.1.5 on 2023-05-13 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(blank=True, choices=[('ORDERED', 'ORDERED'), ('NOT_ORDERED', 'NOT_ORDERED')], default='NOT_ORDERED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 13, 48, 10, 25294)),
        ),
    ]
